apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    labels:
      run: deploy
    name: nginx-deploy 
spec:
  replicas: 2
  selector:
    metchLabels
      run:  deploy-myimage
  template:
    metadata:
      labels:
        run: deploy-myimage
    spec:                        #--> specification
       containers:
       - image: akhilesh9014/jenkinsbuild
         name:  akhilesh9014/jenkinsbuild

         
