apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    labels:
      run: akhilesh9014/jenkinsbuild

    name: nginx-deploy 
spec:
  replicas: 2
  selector:
    metchLabels
      run:  akhilesh9014/jenkinsbuild
  template:
    metadata:
      labels:
        run: akhilesh9014/jenkinsbuild

    spec:                        #--> specification
       containers:
       - image: akhilesh9014/jenkinsbuild
         name:  akhilesh9014/jenkinsbuild

         
