apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: nginx-deploy
    labels: 
      app: deploy-myimage
spec:
  replicas: 2
  selector:
    metchLabels:
      app:  deploy-myimage
  template:
    metadata:
      labels:
        app: deploy-myimage
    spec:                        #--> specification
       containers:
       - name: mybuild_image
         image: akhilesh9014/jenkinsbuild
       ports:
       - containerPort: 80
         
